"""removed required from pathparameters and query parameters

Revision ID: 8fc97128e17c
Revises: cc929b2fd02a
Create Date: 2025-05-31 06:00:58.582297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8fc97128e17c'
down_revision: Union[str, None] = 'cc929b2fd02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pathparameter', 'required')
    op.drop_column('queryparameter', 'required')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queryparameter', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('pathparameter', sa.Column('required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###